### ISSUE TITLE
Support tiling patterns

### ISSUE THREAD

**Issue by hdxpmc** [dmester/pdftosvg.net#12]
Hello
we have tested the pdf file for font type1 + image
type font1 file:
[complexfont1.pdf](https://github.com/dmester/pdftosvg.net/files/12427528/complexfont1.pdf)
it is black at the area of  photos

**Comment by dmester** [comment]
Thanks for the report. The attached file uses two features previously not supported by PdfToSvg.NET: tiling patterns and soft masks. They are now implemented and part of version 0.15.0.
