### ISSUE TITLE
Conversion failed

### ISSUE THREAD

**Issue by thomas-karthe** [dmester/pdftosvg.net#13]
I have a very simple PDF. The converter is crashing!

[rotatedtext.pdf](https://github.com/dmester/pdftosvg.net/files/12682194/rotatedtext.pdf)

**Comment by dmester** [comment]
Thanks for the error report! It should now be fixed in version 0.14.2.

**Comment by thomas-karthe** [comment]
Program is no longer crashing, but there is no <text> in SVG.

**Comment by thomas-karthe** [comment]
there is no `<text>` in SVG

**Comment by dmester** [comment]
The text in this particular PDF is embedded as vector graphics. The vector graphics are included in the exported SVG and what you see on the screen after conversion. The PDF also seems to include the text as invisible text. PdfToSvg.NET does not include invisible text in the export.
