### ISSUE TITLE
Hidden text

### ISSUE THREAD

**Issue by thomas-karthe** [dmester/pdftosvg.net#14]
At a first glance it seems to make no sense of extracting hidden text. But some of the PDF's contain vectorgraphics for exact representation of the content and in parallel there is hidden text, to perform search functionality. 

Hidden text in PDF  could be extracted in a SVG group with invisible text:

	<g class="HiddenText" style="fill:none;">
		<text x="100" y="200">This text is hidden</text>
	</g>
This would allow search also in the SVG. The hidden text can be noticed on Strg-A within the included sample.svg 

<a href="https://github.com/dmester/pdftosvg.net/assets/44520302/3ff38621-52cc-4e73-b583-b71e516b3c54" download>Download sample.svg</a>

**Comment by dmester** [comment]
Thanks for the suggestion. Hidden text is now included from version 0.15.0.
