### ISSUE TITLE
Opt out of style optimization

### ISSUE THREAD

**Issue by markusjohnsson** [dmester/pdftosvg.net#15]
Hello,

I'm hoping to replace our use of Convertio and Inkscape with your fine library. I'm running into an issue with the SVG:s generated though. One of our use cases is to import SVGs into PowerPoint, but PowerPoint does not have support for shorthand font attributes (`font: italic bold 22pt Arial`), they will just become default fonts. However, "longhand" works fine (font-family, font-size, font-weight, font-style).

I noticed in the source code that this is actually an optimisation that is done when outputting style classes and I was curious if you were willing to make it optional? Otherwise I will have to do a post processing step to undo the optimisation. 

I can even provide a PR if you have limited time.

This is the relevant code (SvgRenderer.cs):
<img width="586" alt="image" src="https://github.com/dmester/pdftosvg.net/assets/557685/45c3a01f-0ed0-4a42-912a-ad83a9100894">

**Comment by markusjohnsson** [comment]
Thank you for your quick action on this!

**Comment by dmester** [comment]
The fix is now released as part of version 0.15.0.
