### ISSUE TITLE
Oversized PDF and UserUnit

### ISSUE THREAD

**Issue by thomas-karthe** [dmester/pdftosvg.net#16]
PDF has a size limit of 14.400x14.400 PDFUnits, which is sufficient for common Office documents.
For a document with a dimension larger than 5 meter (´printed on plotter with roll format) however it gets relevant.
(See page 650 of   https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf)

Below is an example of a (empty) 35m long drawing, which is the largest size I met so far.
PDF uses a UserUnit of 7 to represent this drawing within its limits.
That means, that coordinates within the generated SVG have to be multiplied by 7 to get the absolute values.

To achieve correct representation of the SVG, the attributes "width" and "height" should be scaled by the UserUnit (  here x7 ) of the PDF page and the viewBox should be kept as is.  

Not: `<svg width="14173" height="341"  viewBox="0 0 14173.2 340.562" xmlns="http://www.w3.org/2000/svg">`
But:  `<svg width="99212" height="2387" viewBox="0 0 14173.2 340.562" xmlns="http://www.w3.org/2000/svg">`

Sample PDF:  [Userunit.pdf](https://github.com/dmester/pdftosvg.net/files/12858156/Userunit.pdf)

**Comment by dmester** [comment]
Thanks for opening this ticket. This is fixed in version 0.16.0.

**Comment by thomas-karthe** [comment]
UserUnit is now reflecting in SVG width and height. Thanks.
