### ISSUE TITLE
Transparent background

### ISSUE THREAD

**Issue by mmettey** [dmester/pdftosvg.net#18]
Hello,
I found a small issue concerning the handling of transparency on some images.
When converting the pdf page in attachment, we can see that three images on the page, that initially have transparent background, have a white background when converted to svg.

[page-background-issue.pdf](https://github.com/dmester/pdftosvg.net/files/13205513/page-background-issue.pdf)
[page-background-issue-1.svg](https://github.com/dmester/pdftosvg.net/assets/135723810/06d29107-b034-4978-988d-66f6d6d42280)

**Comment by dmester** [comment]
Thanks for reporting this issue. Turns out the images in this PDF are not really transparent, but are using blending modes to simulate transparency. Support for blending modes is added to version 0.16.0 so the PDF should now convert correctly.
