### ISSUE TITLE
Is there any solution to export to html css ?

### ISSUE THREAD

**Issue by hdxpmc** [dmester/pdftosvg.net#22]
Hello
There are many js lib to interact with html div (pan/pinch/rotate) easily. It is difficult to edit svg file (ex: adding video to svg hierarchy, animating svg group, ...). 

We can import svg to html5 canvas (as fabrics, konva, ...) to edit for simple svg file. For large complex svg file, it is very slow responsive and large memory. we can not add  a lot svg to canvas.

Is there any solution to export each svg>g>g to separate svg file with coordinate in the whole svg view box, then later we can put each exported svg file to div inside html ?

Best regards

**Comment by dmester** [comment]
Hello, 

There is no such possibility in the library.

If you need basic modifications like panning and rotation, you can add the SVG directly to the HTML and apply transformations on it using CSS.

If the SVG must be rendered on a canvas frequently and there are performance issues doing so, you can possibly improve performance by prerendering it as a bitmap (using canvas), and then rendering the bitmap on the canvas when needed.
