### ISSUE TITLE
Conversion error on two specific PDF pages

### ISSUE THREAD

**Issue by mmettey** [dmester/pdftosvg.net#27]
Hi,

I just encountered an issue when trying to convert a PDF document, two pages of this document cannot be converted.
These pages are isolated with Ghostscript's latest version, from another PDF file.
I try to convert them one by one, using these commands :

pdftosvg.exe page2.pdf page2.svg --pages 1 --non-interactive --no-color
pdftosvg.exe page29.pdf page29.svg --pages 1 --non-interactive --no-color

I use version 1.2.0 of your library.

The two concerned files :
[page2.pdf](https://github.com/dmester/pdftosvg.net/files/15023049/page2.pdf)
[page29.pdf](https://github.com/dmester/pdftosvg.net/files/15023050/page29.pdf)

Thanks in advance for your kind help.
Let me know if I can provide more information.

**Comment by dmester** [comment]
Thanks for reporting this issue! It is now fixed in version 1.3.0.

**Comment by mmettey** [comment]
Thank you for your quick update, it works fine 👍
