### ISSUE TITLE
Type 1 fonts - Character encoding problem

### ISSUE THREAD

**Issue by cycyrild** [dmester/pdftosvg.net#3]
Hello, I encounter a problem when converting a PDF made from LaTeX source files to SVG. Indeed as you can see on the pictures below some special characters are missing or others are incorrect. I can note that I do not encounter this problem with PDFs made with Word. You will find attached one of the files in question.

SVG output
![](https://drive.google.com/uc?export=download&id=1V6zl55h8dihhDdJ0yox_KgCr4hsPy_jy)

Expected output
![](https://drive.google.com/uc?export=download&id=1eHIduEacxbH97mFIUg-TaTg-82qeSO93)

Link to PDF document
https://drive.google.com/file/d/1L0jBDQKHZ78WB-jKuri1AGj2SrkvlXrD/view?usp=share_link

**Comment by dmester** [comment]
Thanks for reporting this issue and sorry for the delayed answer. A PDF can contain several font formats, not all of them yet being implemented by PdfToSvg.NET. You can see the implemented format here:

**Comment by dmester** [comment]
Type 1 font support was added in version 0.9.0, so the library should now be able to handle the file you have linked.
