### ISSUE TITLE
How to resolve garbled characters during file conversion? 

### ISSUE THREAD

**Issue by cquan123** [dmester/pdftosvg.net#30]
[汽车销售人员绩效考核方案[精品文档].pdf](https://github.com/user-attachments/files/16007400/default.pdf)
![image](https://github.com/dmester/pdftosvg.net/assets/115888035/32d4ef24-0752-4cdd-9ce3-0b0cceebc399)

**Comment by dmester** [comment]
Thanks for reporting this issue. A fix is included in version 1.4.0.

**Comment by cquan123** [comment]
Thanks
