### ISSUE TITLE
PDF to SVG folder structure mismatching

### ISSUE THREAD

**Issue by anbarasakumar** [dmester/pdftosvg.net#31]
Before reporting an issue, please ensure:

When converting the PDF to SVG the folder structure is not matching with PDF. below is my used code

try
{
    using (var doc = PdfDocument.Open(@"E:\PdfToSvg\Pdf\" + fileName + ".pdf"))
    {
        var pageNo = 1;
        var option = new SvgConversionOptions();
        foreach (var page in doc.Pages)
        {
            page.SaveAsSvg(@"E:\PdfToSvg\Svg\" + fileName + "-" + pageNo.ToString() + ".svg", option);
            pageNo++;
        }
    }
    return true;
}

* Your issue is not regarding a non-supported feature. See [Limitations](https://github.com/dmester/pdftosvg.net/blob/master/docs/limitations.md).
* You have provided a link to the PDF file that cannot be converted (if applicable).
![image](https://github.com/dmester/pdftosvg.net/assets/155613984/607f3cde-5b4b-42d6-9f2f-0da38c33f137)
![image](https://github.com/dmester/pdftosvg.net/assets/155613984/b3519307-8881-44a0-b261-49d3b1f68ddf)
![image](https://github.com/dmester/pdftosvg.net/assets/155613984/2359ad81-6a7f-4a19-836f-3820c5f284b8)

**Comment by dmester** [comment]
The XML structure of the SVG is optimized for size.

Just to understand what you are trying to do, what is the use case where you need the groups? If it is for editing, can you import the PDF directly into your vector editor?

**Comment by dmester** [comment]
Closed due to inactivity
