### ISSUE TITLE
Symbols conversion issue

### ISSUE THREAD

**Issue by sergvdm** [dmester/pdftosvg.net#32]
For some documents symbols (e.g. Celsius degree symbol, or Greek letter) not converted correctly. For example:

PDF:<img width="226" alt="pdf1" src="https://github.com/user-attachments/assets/676fea10-2a7c-4f8b-bb29-c9be021703ba">
SVG:<img width="248" alt="svg1" src="https://github.com/user-attachments/assets/721b4df9-395f-41c3-b97b-dd37f8660996">

PDF:<img width="235" alt="pdf2" src="https://github.com/user-attachments/assets/e111ddfe-ffa7-4ab9-b594-ea8cce3f47c1">
SVG:<img width="253" alt="svg2" src="https://github.com/user-attachments/assets/283d6e95-fb07-479c-9c2c-26f3489a5ccd">

It seems to be something wrong with font /F14, here piece of content buffer related to first picture:
Tm_(< 25)Tj_/F14 → 1 Tf_1.7474 0 TD_0 Tw_(m)Tj_/F9

Example pdf: 
[getdatasheetpartid-359780-15107033.pdf](https://github.com/user-attachments/files/16279818/getdatasheetpartid-359780-15107033.pdf)

**Comment by dmester** [comment]
Thanks for reporting this issue. A fix will be included in the next release. I will get back to you when it is published.

**Comment by sergvdm** [comment]
Thank you!

**Comment by dmester** [comment]
A fix is now released as part of version 1.4.1.
