### ISSUE TITLE
Text conversion issue

### ISSUE THREAD

**Issue by sergvdm** [dmester/pdftosvg.net#33]
For some documents some font glyphs are not placed correctly. For example:

PDF:<img width="365" alt="pdf3" src="https://github.com/user-attachments/assets/5ea26c06-fa04-4bda-b069-fb47357378a1">
SVG:<img width="349" alt="svg3" src="https://github.com/user-attachments/assets/420dcf5c-bce6-4a16-89d2-357ec682b93e">

Example pdf:
[tajlp-282895.pdf](https://github.com/user-attachments/files/16327396/tajlp-282895.pdf)

**Comment by dmester** [comment]
Thanks for reporting this issue! It is now fixed in version 1.4.1.
