### ISSUE TITLE
How to handle minor garbling when converting a PDF to SVG?

### ISSUE THREAD

**Issue by cquan123** [dmester/pdftosvg.net#35]
[f73d780f3beb43a1825cfdf54a6278e8.pdf](https://github.com/user-attachments/files/16519224/f73d780f3beb43a1825cfdf54a6278e8.pdf)
![image](https://github.com/user-attachments/assets/a0af1cbb-884e-47ff-b315-e96036817e0a)

**Comment by dmester** [comment]
Thanks for reporting this issue. Version 1.5.0 should now be able to convert the document you have provided without the garbage characters.
