### ISSUE TITLE
Checkbox and radiobutton missing

### ISSUE THREAD

**Issue by FredKors** [dmester/pdftosvg.net#37]
Hello!

Is doing some testing with your library and I have to say it performs pretty well. The only thing I noticed is that it doesn't render checkboxes and radiobuttons (while text fields, buttons, lists and comboboxes work fine). I looked at the code a bit and was able to render checkboxes and radiobuttons with just a few lines of code.

I modified the function RenderAnnotationAppearance in this way:

```
private void RenderAnnotationAppearance(PdfDictionary annot, int? fileIndex)
{
    if (!annot.TryGetDictionary(Names.AP / Names.N, out var normalAppearance) ||
        !annot.TryGetRectangle(Names.Rect, out var rect))
    {
        return;
    }

    if (annot.TryGetName(Names.AS, out var aspect))
    {
        if (!normalAppearance.TryGetDictionary(value, out aspect))
        {
            return;
        }
    }

...
```

and in the file Names.cs I defined

```
        public static PdfName AS { get; } = new PdfName("AS");
```

That's all!

**Comment by dmester** [comment]
Thanks for reporting this issue. I have included the fix in version 1.5.0.
