### ISSUE TITLE
Specific font issue

### ISSUE THREAD

**Issue by mmettey** [dmester/pdftosvg.net#6]
Hi, first I wanna thank you for sharing your great work here.
This library is the most reliable one to suit almost all my needs, great work ! 👍 

I just have a very specific font issue today :

I am converting PDF pages, one by one, splitted by another library, named Ghostscript.

For the same PDF source file :

- It works well when the PDF page is generated by Ghostscript v9.23 :

Source PDF :

![image](https://github.com/dmester/pdftosvg.net/assets/135723810/c6323827-1eaa-4007-b4eb-f7e93e498a86)

SVG ouput :

![image](https://github.com/dmester/pdftosvg.net/assets/135723810/fb4ba65a-e659-4a06-a41b-39b43565ae04)

[Link to PDF source file](https://drive.google.com/file/d/1Xjn3aU0K9Irer3MZwON3te9GZ3m_s1ZV/view?usp=sharing)
[Link to generated SVG](https://drive.google.com/file/d/17E3b4_4q16lTyZEGCl0eD2m6Y4ctHQlm/view?usp=sharing)

- The font family does not display in the SVG file when the source PDF file is generated by Ghostscript v10+ (though, the font is well displayed on the PDF file) :

Source PDF :

![image](https://github.com/dmester/pdftosvg.net/assets/135723810/c179b786-577a-47e5-9b99-5c5f33859e16)

SVG ouput :

![image](https://github.com/dmester/pdftosvg.net/assets/135723810/35278e9a-05ce-445f-a81a-d7eb85825082)

[Link to PDF source file](https://drive.google.com/file/d/1JeVqmthEx3BOD2-VOZGMTuu5pvT2k3yl/view?usp=sharing)
[Link to generated SVG](https://drive.google.com/file/d/1ZXD0bVHls3-ioxpaulVFvZWEXAZdXUeV/view?usp=sharing)

It seems that the generated @font-face in the SVG file is not working here, I tried to manually replace it by the same @font-face than the first SVG, and everything looks fine. I assume that the font format is a little different due to Ghostscript version. I am aware that Ghostscript is not your concern, but as the font is well displayed in the PDF file, maybe there is a particular case to take into consideration ?

Let me know if I can provide additional information.

**Comment by dmester** [comment]
Thanks for reporting this issue and I'm glad to hear that you find it reliable. 

There was a metric (ExpansionFactor in the CFF PrivateDict) in the font that the browser didn't like. It should be fixed in version 0.13.0.

**Comment by mmettey** [comment]
Wow, many thanks for reacting so promptly, everything is fine now 👍
