### ISSUE TITLE
Text shifted

### ISSUE THREAD

**Issue by ftovagliari** [dmester/pdftosvg.net#8]
Hello, 
pdftosvg worked very well on all the documents I tried but I report a problem with the following file:
[Link to PDF](https://github.com/dmester/pdftosvg.net/files/12064599/newstar.pdf)
from which I get this output:
[Link to SVG](https://github.com/dmester/pdftosvg.net/assets/582712/25160696-d069-4082-bf4e-2ae31a04b9ac)
As you can see from the SVG, all the text is shifted up from what the PDF viewer is showing.

PDF viewer
![image](https://github.com/dmester/pdftosvg.net/assets/582712/e581106c-56b3-4f49-a562-6a011400b547)
SVG viewer
![image](https://github.com/dmester/pdftosvg.net/assets/582712/41c8d353-7500-4580-976f-e978b726a2b9)

Thanks.

**Comment by dmester** [comment]
Thanks for reporting this issue. It should now be fixed in version 0.13.1.
