### ISSUE TITLE
Courier font too large

### ISSUE THREAD

**Issue by ftovagliari** [dmester/pdftosvg.net#9]
I found an issue with this pdf:
[PDF](https://github.com/dmester/pdftosvg.net/files/12065042/figc.pdf)
page 3 is converted as follows:
[SVG](https://github.com/dmester/pdftosvg.net/assets/582712/0554205c-c258-424b-958a-9adb23362f0c)
Courier font seems too large.

Thank you very much.

**Comment by dmester** [comment]
Thanks for reporting the issue. It should be fixed in version 0.14.0.
